### PR TITLE
Make the names look nicer

### PR DESCRIPTION
**Pull request by ogndrahcir**
Highlighting VODs, I've noticed the names are very ugly if they aren't capitalized.

### CODE REVIEW

**Comment by meldontaragon** [comment]
People have capitalization preferences that you can check from their Twitch channel and this goes against it. We should use what they want for their name, not what we think looks better.

**Comment by jhobz** [comment]
I actually don't necessarily agree @david-c-miller . Standardizing everything to uppercase isn't an uncommon practice and is usually used specifically to make things look better. I also recall Vulajin bringing up the idea of capitalized text for the stats callout last tournament for this same reason.

Specifically though @ogndrahcir , where are you noticing it looking worse? Splash screen? Brackets? We don't necessarily have to apply the same solution everywhere if it looks fine in one but not another.

**Comment by jhobz** [comment]
lmao this is a PR and not an issue, I'm an idiot. One moment, answering my last question myself...

**Comment by jhobz** [comment]
Ok so in this instance, I actually do agree with Meldon. We shouldn't capitalize the first letter of someone's name if they specifically enter it as uncapitalized (ex: you left your own name with a lowercase 'o' in this commit). I misunderstood the initial comment and thought this was referring to full capitalization of the names. _That_ is something I'd be down to consider, but not this commit as it currently stands.

**Comment by ogndrahcir** [comment]
Yeah Meldon addressed it in Discord a while ago already. Also so I know my name is "ogNdrahciR" not "ogndrahcir" (capital R and N) as it's spelled here. 

I don't have the time to look through everyone's name to make sure they're up to date, and I don't care enough to change it now that it's 5 weeks into swiss anyways, but something going forward, for other tournaments, we definitely want to make sure capitalization is correct for names.

**Pull request closed without merging**
